/**
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. OpenMRS is also distributed under
 * the terms of the Healthcare Disclaimer located at http://openmrs.org/license.
 *
 * Copyright (C) OpenMRS Inc. OpenMRS is a registered trademark and the OpenMRS
 * graphic logo is a trademark of OpenMRS Inc.
 */
package org.openmrs.module.chartsearchai.api;

import java.util.Date;
import java.util.List;
import java.util.function.Consumer;

import org.openmrs.Patient;
import org.openmrs.module.chartsearchai.reference.SafetyWarning;

/**
 * Answers natural language questions about a patient's chart using a local LLM.
 * When {@code chartsearchai.embedding.preFilter} is {@code true} (default), uses
 * embedding similarity to narrow records to the most relevant ones before sending
 * them to the LLM. Set to {@code false} to send the full patient chart instead.
 */
public interface ChartSearchService {

	/**
	 * Search a patient's chart using a natural language question.
	 *
	 * @param patient the patient whose chart to query
	 * @param question the clinician's natural language question
	 * @return the answer with source references for citation linking
	 */
	ChartAnswer search(Patient patient, String question);

	/**
	 * Streaming variant of {@link #search}. Calls the tokenConsumer for each token as
	 * it is generated by the LLM, then returns the complete answer with references.
	 *
	 * @param patient the patient whose chart to query
	 * @param question the clinician's natural language question
	 * @param tokenConsumer called with each token fragment as it is generated
	 * @return the complete answer with source references
	 */
	ChartAnswer searchStreaming(Patient patient, String question, Consumer<String> tokenConsumer);

	/**
	 * Streaming variant that additionally forwards the model's reasoning (chain-of-thought) to
	 * {@code reasoningConsumer} as it is generated, so a caller can surface it as a live "thinking"
	 * indicator. The answer stream to {@code tokenConsumer} is unchanged. Default implementation
	 * ignores reasoning and delegates to the three-arg variant, so existing implementations and
	 * callers are unaffected.
	 *
	 * @param patient the patient whose chart to query
	 * @param question the clinician's natural language question
	 * @param tokenConsumer called with each answer-text fragment as it is generated
	 * @param reasoningConsumer called with each reasoning-text fragment as it is generated
	 * @return the complete answer with source references
	 */
	default ChartAnswer searchStreaming(Patient patient, String question, Consumer<String> tokenConsumer,
			Consumer<String> reasoningConsumer) {
		return searchStreaming(patient, question, tokenConsumer);
	}

	/**
	 * Streaming variant that additionally forwards the answer's citations to {@code citationsConsumer}
	 * the moment the answer is generated — <em>before</em> the citation-grounding pass — so a caller
	 * can render the answer and its clickable citations immediately and let grounding verdicts arrive
	 * afterwards. Grounding (Tier-2 entailment) can add a tail of LLM work; this keeps it off the
	 * path to a readable, cited answer. The returned {@link ChartAnswer} still carries the fully
	 * grounded references. The default ignores {@code citationsConsumer} and delegates to the four-arg
	 * variant, so existing implementations and callers are unaffected.
	 *
	 * @param citationsConsumer called once with the answer's references <em>before</em> grounding
	 *        (verdicts not yet attached); the returned answer carries the grounded references
	 * @return the complete answer with grounded source references
	 */
	default ChartAnswer searchStreaming(Patient patient, String question, Consumer<String> tokenConsumer,
			Consumer<String> reasoningConsumer, Consumer<List<RecordReference>> citationsConsumer) {
		return searchStreaming(patient, question, tokenConsumer, reasoningConsumer);
	}

	/**
	 * Streaming variant that additionally hands the caller the <em>complete but not yet
	 * grounding-verified</em> answer the moment it exists, via {@code ungroundedAnswerConsumer} —
	 * the seam that lets the REST layer finish the user-visible response (emit its {@code done}
	 * event, persist the audit row) without waiting out the citation-grounding tail, which on
	 * CPU-only deployments adds seconds of Tier-2 LLM work after the answer is already readable.
	 *
	 * <p>The consumer contract:</p>
	 * <ul>
	 *   <li>It fires at most ONCE, after the answer and its citation references are final but
	 *       before grounding verification runs; the references it carries have {@code null}
	 *       verdicts.</li>
	 *   <li>It fires on the live inference path regardless of whether grounding is enabled —
	 *       its meaning is "the answer is complete", not "grounding will follow".</li>
	 *   <li>It does NOT fire when the implementation returns an answer that is already final —
	 *       e.g. a cached answer, whose verdicts were attached when it was first computed. A
	 *       caller that emitted nothing from the consumer must therefore fall back to treating
	 *       the returned {@link ChartAnswer} as the single, final result.</li>
	 * </ul>
	 *
	 * <p>This overload is deliberately abstract, not a default: every implementation —
	 * especially delegating wrappers like the caching router — must decide explicitly how to
	 * route the consumer. A defaulted implementation that silently dropped it would re-create
	 * the consumer-loss bug class that the citations channel hit before (see the history on the
	 * five-arg overload).</p>
	 *
	 * @param ungroundedAnswerConsumer called at most once with the complete answer whose
	 *        references carry no grounding verdicts yet; not called for already-final answers
	 * @return the complete answer with grounded source references, exactly as the five-arg
	 *         overload returns
	 */
	ChartAnswer searchStreaming(Patient patient, String question, Consumer<String> tokenConsumer,
			Consumer<String> reasoningConsumer, Consumer<List<RecordReference>> citationsConsumer,
			Consumer<ChartAnswer> ungroundedAnswerConsumer);

	/**
	 * Streaming variant that additionally routes the progressive-reasoning PREVIEW pass's reasoning
	 * to {@code preliminaryReasoningConsumer} — a separate channel from {@code reasoningConsumer} —
	 * so a caller can render it as provisional (clearly an in-progress preview, not the answer) and
	 * replace it the moment the committed full-chart reasoning begins arriving on
	 * {@code reasoningConsumer}. Only fires when
	 * {@code chartsearchai.progressiveReasoning.enabled} is on (otherwise the preliminary channel is
	 * never called and this behaves exactly like the six-arg overload).
	 *
	 * <p>The default delegates to the six-arg overload, which routes any preview reasoning to
	 * {@code reasoningConsumer} (merged, not separated) — so an implementation that does not override
	 * this still SHOWS preview reasoning, it just does not split it onto its own channel. Concrete
	 * streaming implementations and delegating wrappers (the caching router) override this to route
	 * the preliminary channel explicitly, the same discipline the six-arg overload's abstractness
	 * enforces for the ungrounded-answer channel.
	 *
	 * <p><strong>Override discipline:</strong> an implementation whose six-arg overload delegates
	 * <em>up</em> to this seven-arg (as the inference service and the caching router do) MUST also
	 * override this seven-arg — relying on this default while the six-arg delegates up would recurse
	 * (default → six-arg → this default → …).
	 *
	 * @param preliminaryReasoningConsumer called with each preview-reasoning fragment; never called
	 *        when progressive reasoning is off or no relevant records are found
	 */
	default ChartAnswer searchStreaming(Patient patient, String question, Consumer<String> tokenConsumer,
			Consumer<String> reasoningConsumer, Consumer<List<RecordReference>> citationsConsumer,
			Consumer<ChartAnswer> ungroundedAnswerConsumer, Consumer<String> preliminaryReasoningConsumer) {
		return searchStreaming(patient, question, tokenConsumer, reasoningConsumer, citationsConsumer,
				ungroundedAnswerConsumer);
	}

	/**
	 * Pre-warm any patient-specific caches (serialized chart, LLM prompt cache) so the
	 * first real query on this patient does not pay cold-start cost. Implementations
	 * that don't support warmup may return immediately. Callers should treat this as
	 * fire-and-forget — failures must not propagate.
	 *
	 * @param patient the patient whose chart to warm up
	 */
	default void warmup(Patient patient) {
	}

	/**
	 * Whether this service keeps an answer cache that is currently active. Only the caching router
	 * returns {@code true}; a plain inference service has no cache. Lets the write-side AOP indexing
	 * advice decide whether a chart write needs to invalidate anything <em>before</em> resolving the
	 * affected patient, so the cache-off hot path skips that work. Default: no cache.
	 *
	 * @return {@code true} if a repeated identical query may currently be served from cache
	 */
	default boolean isCacheEnabled() {
		return false;
	}

	/**
	 * Evict any cached answers for one patient after their chart changes, so a repeated identical
	 * question recomputes against the new chart instead of serving a stale answer. A no-op for
	 * implementations without a cache. Called from the AOP write advice on every chart write,
	 * regardless of which retrieval backend is active.
	 *
	 * @param patientUuid the uuid of the patient whose cached answers to drop
	 */
	default void invalidatePatient(String patientUuid) {
	}

	/**
	 * An answer to a chart search question with source citations.
	 */
	class ChartAnswer {

		private final String answer;

		private final List<RecordReference> references;

		private final int inputTokens;

		private final int outputTokens;

		private final int cachedTokens;

		private final List<SafetyWarning> safetyWarnings;

		public ChartAnswer(String answer, List<RecordReference> references) {
			this(answer, references, 0, 0, 0);
		}

		public ChartAnswer(String answer, List<RecordReference> references,
				int inputTokens, int outputTokens) {
			this(answer, references, inputTokens, outputTokens, 0);
		}

		public ChartAnswer(String answer, List<RecordReference> references,
				int inputTokens, int outputTokens, int cachedTokens) {
			this(answer, references, inputTokens, outputTokens, cachedTokens,
					java.util.Collections.<SafetyWarning> emptyList());
		}

		public ChartAnswer(String answer, List<RecordReference> references,
				int inputTokens, int outputTokens, int cachedTokens,
				List<SafetyWarning> safetyWarnings) {
			this.answer = answer;
			this.references = java.util.Collections.unmodifiableList(
					new java.util.ArrayList<>(references));
			this.inputTokens = inputTokens;
			this.outputTokens = outputTokens;
			this.cachedTokens = cachedTokens;
			this.safetyWarnings = java.util.Collections.unmodifiableList(
					new java.util.ArrayList<>(safetyWarnings == null
							? java.util.Collections.<SafetyWarning> emptyList() : safetyWarnings));
		}

		/**
		 * The response text, which may contain numbered citation labels in brackets
		 * (e.g. [1], [3]).
		 */
		public String getAnswer() {
			return answer;
		}

		/**
		 * The ordered list of record references cited in the answer.
		 */
		public List<RecordReference> getReferences() {
			return references;
		}

		/**
		 * The number of input (prompt) tokens used.
		 */
		public int getInputTokens() {
			return inputTokens;
		}

		/**
		 * The number of output (completion) tokens used.
		 */
		public int getOutputTokens() {
			return outputTokens;
		}

		/**
		 * The number of input tokens that were served from llama-server's prompt cache
		 * (i.e., reused from a prior request's KV) instead of being processed fresh.
		 */
		public int getCachedTokens() {
			return cachedTokens;
		}

		/**
		 * Non-blocking drug-safety advisories raised by the post-answer validator
		 * (overdose / interaction / contraindication). Empty when the drug-reference
		 * feature is disabled or nothing was flagged. These annotate the answer; they
		 * never alter or suppress it.
		 */
		public List<SafetyWarning> getSafetyWarnings() {
			return safetyWarnings;
		}
	}

	/**
	 * Identifies a source record in OpenMRS cited by the LLM answer.
	 */
	class RecordReference {

		private final int index;

		private final String resourceType;

		private final String resourceUuid;

		private final Date date;

		private final Boolean grounded;

		public RecordReference(int index, String resourceType, String resourceUuid, Date date) {
			this(index, resourceType, resourceUuid, date, null);
		}

		public RecordReference(int index, String resourceType, String resourceUuid, Date date, Boolean grounded) {
			this.index = index;
			this.resourceType = resourceType;
			this.resourceUuid = resourceUuid;
			this.date = date;
			this.grounded = grounded;
		}

		public int getIndex() {
			return index;
		}

		public String getResourceType() {
			return resourceType;
		}

		public String getResourceUuid() {
			return resourceUuid;
		}

		public Date getDate() {
			return date;
		}

		/**
		 * Whether the cited record was found to actually support the answer
		 * sentence(s) that cite it. {@code TRUE}/{@code FALSE} when grounding
		 * verification ran (see {@code chartsearchai.grounding.enabled});
		 * {@code null} when verification was disabled or could not run for this
		 * reference (e.g. the record carried no text to compare against). A
		 * {@code null} verdict must be rendered as "unverified", never as
		 * "verified".
		 */
		public Boolean getGrounded() {
			return grounded;
		}

		/**
		 * @return a copy of this reference carrying the given grounding verdict
		 */
		public RecordReference withGrounded(Boolean verdict) {
			return new RecordReference(index, resourceType, resourceUuid, date, verdict);
		}
	}
}
