/**
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. OpenMRS is also distributed under
 * the terms of the Healthcare Disclaimer located at http://openmrs.org/license.
 *
 * Copyright (C) OpenMRS Inc. OpenMRS is a registered trademark and the OpenMRS
 * graphic logo is a trademark of OpenMRS Inc.
 */
package org.openmrs.module.chartsearchai.api;

import java.util.Date;
import java.util.List;
import java.util.function.Consumer;

import org.openmrs.Patient;

/**
 * Answers natural language questions about a patient's chart using a local LLM.
 * When {@code chartsearchai.embedding.preFilter} is {@code true} (default), uses
 * embedding similarity to narrow records to the most relevant ones before sending
 * them to the LLM. Set to {@code false} to send the full patient chart instead.
 */
public interface ChartSearchService {

	/**
	 * Search a patient's chart using a natural language question.
	 *
	 * @param patient the patient whose chart to query
	 * @param question the clinician's natural language question
	 * @return the answer with source references for citation linking
	 */
	ChartAnswer search(Patient patient, String question);

	/**
	 * Streaming variant of {@link #search}. Calls the tokenConsumer for each token as
	 * it is generated by the LLM, then returns the complete answer with references.
	 *
	 * @param patient the patient whose chart to query
	 * @param question the clinician's natural language question
	 * @param tokenConsumer called with each token fragment as it is generated
	 * @return the complete answer with source references
	 */
	ChartAnswer searchStreaming(Patient patient, String question, Consumer<String> tokenConsumer);

	/**
	 * Pre-warm any patient-specific caches (serialized chart, LLM prompt cache) so the
	 * first real query on this patient does not pay cold-start cost. Implementations
	 * that don't support warmup may return immediately. Callers should treat this as
	 * fire-and-forget — failures must not propagate.
	 *
	 * @param patient the patient whose chart to warm up
	 */
	default void warmup(Patient patient) {
	}

	/**
	 * An answer to a chart search question with source citations.
	 */
	class ChartAnswer {

		private final String answer;

		private final List<RecordReference> references;

		private final List<org.openmrs.module.chartsearchai.api.impl.ResponseBlock> blocks;

		private final int inputTokens;

		private final int outputTokens;

		private final int cachedTokens;

		public ChartAnswer(String answer, List<RecordReference> references) {
			this(answer, references, java.util.Collections.emptyList(), 0, 0, 0);
		}

		public ChartAnswer(String answer, List<RecordReference> references,
				int inputTokens, int outputTokens) {
			this(answer, references, java.util.Collections.emptyList(), inputTokens, outputTokens, 0);
		}

		public ChartAnswer(String answer, List<RecordReference> references,
				int inputTokens, int outputTokens, int cachedTokens) {
			this(answer, references, java.util.Collections.emptyList(),
					inputTokens, outputTokens, cachedTokens);
		}

		public ChartAnswer(String answer, List<RecordReference> references,
				List<org.openmrs.module.chartsearchai.api.impl.ResponseBlock> blocks,
				int inputTokens, int outputTokens, int cachedTokens) {
			this.answer = answer;
			this.references = java.util.Collections.unmodifiableList(
					new java.util.ArrayList<>(references));
			this.blocks = blocks == null
					? java.util.Collections.emptyList()
					: java.util.Collections.unmodifiableList(new java.util.ArrayList<>(blocks));
			this.inputTokens = inputTokens;
			this.outputTokens = outputTokens;
			this.cachedTokens = cachedTokens;
		}

		/**
		 * The response text, which may contain numbered citation labels in brackets
		 * (e.g. [1], [3]).
		 */
		public String getAnswer() {
			return answer;
		}

		/**
		 * The ordered list of record references cited in the answer.
		 */
		public List<RecordReference> getReferences() {
			return references;
		}

		/**
		 * Structured non-prose blocks (tables today; lists/timelines/etc. later)
		 * the LLM chose to emit. Empty when the answer is prose-only.
		 */
		public List<org.openmrs.module.chartsearchai.api.impl.ResponseBlock> getBlocks() {
			return blocks;
		}

		/**
		 * The number of input (prompt) tokens used.
		 */
		public int getInputTokens() {
			return inputTokens;
		}

		/**
		 * The number of output (completion) tokens used.
		 */
		public int getOutputTokens() {
			return outputTokens;
		}

		/**
		 * The number of input tokens that were served from llama-server's prompt cache
		 * (i.e., reused from a prior request's KV) instead of being processed fresh.
		 */
		public int getCachedTokens() {
			return cachedTokens;
		}
	}

	/**
	 * Identifies a source record in OpenMRS cited by the LLM answer.
	 */
	class RecordReference {

		private final int index;

		private final String resourceType;

		private final String resourceUuid;

		private final Date date;

		public RecordReference(int index, String resourceType, String resourceUuid, Date date) {
			this.index = index;
			this.resourceType = resourceType;
			this.resourceUuid = resourceUuid;
			this.date = date;
		}

		public int getIndex() {
			return index;
		}

		public String getResourceType() {
			return resourceType;
		}

		public String getResourceUuid() {
			return resourceUuid;
		}

		public Date getDate() {
			return date;
		}
	}
}
